version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: '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'
      SECRET_KEY: 'my-secret-key'
      DATABASE_URI: 'postgresql://postgres:FunnelHQ@database-1.cv0om20okbqv.eu-north-1.rds.amazonaws.com:5432/Questionaire-2'
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./frontend:/usr/src/frontend

volumes:
  pgdata:  # Removed the PostgreSQL data volume
